<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<!--  <a href="<?php //echo $this->url($this->route, array('page' => $this->previous)); ?>">
     Prev
  </a> -->
<span class='pageinate' id="pg_<?php echo $this->previous; ?>">Prev</span>
<?php else: ?>
  <span  class="disabled">Prev</span> 
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
<!--    <a href="<?php //echo $this->url($this->route, array('page' => $page)); ?>">
        <?php //echo $page; ?>
    </a> -->
<span class='pageinate' id="pg_<?php echo $page; ?>"> <?php echo $page; ?></span>
  <?php else: ?>
 <span class='pageinate rmv_clr' style='color:#2357BB' id="pg_<?php echo $page; ?>"> <?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<!--  <a href="<?php //echo $this->url($this->route, array('page' => $this->next)); ?>">
    Next 
  </a>-->
<span class='pageinate' id="pg_<?php echo $this->next; ?>">Next</span>
<?php else: ?>
  <span class="disabled">Next</span>
<?php endif; ?>
</div>
<?php endif; ?>